name: sync glue scripts to s3

on:
  push:
    branches: [feat/1-batch-ingestion-full-vs-incremental]
    paths: 
      - 'glue/**'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync glue/ s3://sh26-aws-ingestion-tf/1-batch-ingestion-full-vs-incremental/glue/scripts/
